// next/src/app/crew/page.tsx
'use client';

import { useEffect, useState, useMemo } from "react";
import axios from "axios";

import BodyClass from "@/app/components/BodyClass";

interface ICrewItem {
  bio: string;
  images: {
    webp: string;
    png: string;
  }
  name: string;
  role: string;
}

export default function Page() {
  const [data, setData] = useState<ICrewItem[]>([]);
  const [active, setActive] = useState<number>(0);

  const item: ICrewItem | false = useMemo(() => data.length > 0 && data[active], [active, data]);

  useEffect(() => {
    getData();
  }, [])

  const getData = async () => {
    const {data} = await axios.get('/api/crew')
    setData(data);
  }

  return (
    <main id="main" className="grid-container grid-container--crew flow">
      <BodyClass bodyClass="crew" />
      <h1 className="numbered-title"><span aria-hidden="true">02</span> Meet your crew</h1>

      {item && <>
        <div className="dot-indicators flex">
          {data.map((item: ICrewItem, index: number) => (
            <button onClick={() => setActive(index)} aria-selected={index === active ? 'true' : 'false'} role="tab" key={index}>
              <span className="sr-only">The {item.name}</span>
            </button>
          ))}
        </div>

        <article className="crew-details flow" id="commander-tab">
          <header className="flow flow--space-small">
            <h2 className="fs-600 ff-serif uppercase">{item.role}</h2>
            <p className="fs-700 uppercase ff-serif">{item.name}</p>
          </header>
          <p>{item.bio}</p>
        </article>

        <picture>
          <source srcSet={item.images.webp} type="image/webp" />
          <img src={item.images.png} alt={item.name} />
        </picture>
      </>}

    </main>
  );
}

// angular/src/app/crew/crew.component.ts
import { Component, OnInit } from '@angular/core';
import { CrewService, ICrewItem } from "../crew.service";

@Component({
  selector: 'app-crew',
  moduleId: 'page',
  templateUrl: './crew.component.html',
  styleUrls: ['./crew.component.scss'],
})
export class CrewComponent implements OnInit {
  items: ICrewItem[] = [];
  active: number = 0;
  activeItem?: ICrewItem;

  constructor(private crewService: CrewService) {}

  ngOnInit(): void {
    window.document.body.classList.add("crew");

    this.items = this.crewService.getItems();
    this.activeItem = this.items[this.active];
  }

  ngOnDestroy(): void {
    window.document.body.classList.remove("crew");
  }

  change(index: number) {
    this.active = index;
    this.activeItem = this.items[this.active];
  }
}

<main id="main" class="grid-container grid-container--crew flow">
  <h1 class="numbered-title"><span aria-hidden="true">02</span> Meet your crew</h1>

  <div class="dot-indicators flex" role="tablist" aria-label="crew member list">
    <button
      *ngFor="let item of items; index as i;"
      (click)="change(i)"
      [attr.aria-selected]="i === active ? 'true' : 'false'"
      role="tab"><span class="sr-only">The {{item.name}}</span></button>
  </div>

  <article class="crew-details flow">
    <header class="flow flow--space-small">
      <h2 class="fs-600 ff-serif uppercase">{{activeItem && activeItem.role}}</h2>
      <p class="fs-700 uppercase ff-serif">{{activeItem && activeItem.name}}</p>
    </header>
    <p>{{activeItem && activeItem.bio}}</p>
  </article>


  <picture id="commander-image">
    <source srcset="{{activeItem && activeItem.images.webp}}" type="image/webp">
    <img src="{{activeItem && activeItem.images.png}}" alt="{{activeItem && activeItem.name}}">
  </picture>
</main>
