// angular/src/app/crew/crew.component.ts
import { Component, OnInit } from '@angular/core';
import { CrewService, ICrewItem } from "../crew.service";

@Component({
  selector: 'app-crew',
  moduleId: 'page',
  templateUrl: './crew.component.html',
  styleUrls: ['./crew.component.scss'],
})
export class CrewComponent implements OnInit {
  items: ICrewItem[] = [];
  active: number = 0;
  activeItem?: ICrewItem;

  constructor(private crewService: CrewService) {}

  ngOnInit(): void {
    window.document.body.classList.add("crew");

    this.items = this.crewService.getItems();
    this.activeItem = this.items[this.active];
  }

  ngOnDestroy(): void {
    window.document.body.classList.remove("crew");
  }

  change(index: number) {
    this.active = index;
    this.activeItem = this.items[this.active];
  }
}

<main id="main" class="grid-container grid-container--crew flow">
  <h1 class="numbered-title"><span aria-hidden="true">02</span> Meet your crew</h1>

  <div class="dot-indicators flex" role="tablist" aria-label="crew member list">
    <button
      *ngFor="let item of items; index as i;"
      (click)="change(i)"
      [attr.aria-selected]="i === active ? 'true' : 'false'"
      role="tab"><span class="sr-only">The {{item.name}}</span></button>
  </div>

  <article class="crew-details flow">
    <header class="flow flow--space-small">
      <h2 class="fs-600 ff-serif uppercase">{{activeItem && activeItem.role}}</h2>
      <p class="fs-700 uppercase ff-serif">{{activeItem && activeItem.name}}</p>
    </header>
    <p>{{activeItem && activeItem.bio}}</p>
  </article>


  <picture id="commander-image">
    <source srcset="{{activeItem && activeItem.images.webp}}" type="image/webp">
    <img src="{{activeItem && activeItem.images.png}}" alt="{{activeItem && activeItem.name}}">
  </picture>
</main>

// react/src/pages/crew.tsx
import React, { useEffect, useState, useMemo } from "react";

import data from "data.json";

const Crew = () => {

  const [active, setActive] = useState(0);

  const person = useMemo(() => data.crew[active], [active]);

  useEffect(() => {
    document.body.classList.add("crew");

    return () => {
      document.body.classList.remove("crew");
    }
  });

  return (<main id="main" className="grid-container grid-container--crew flow">
    <h1 className="numbered-title"><span aria-hidden="true">02</span> Meet your crew</h1>

    <div className="dot-indicators flex" role="tablist" aria-label="crew member list">
      {data.crew.map(({role}, index) => {
        return (<button key={role} onClick={() => setActive(index)} aria-selected={active === index ? "true" : "false"} role="tab">
          <span className="sr-only">The {role}</span></button>)
      })}
    </div>

    <article className="crew-details flow" id="commander-tab" role="tabpanel">
      <header className="flow flow--space-small">
        <h2 className="fs-600 ff-serif uppercase">{person.role}</h2>
        <p className="fs-700 uppercase ff-serif">{person.name}</p>
      </header>
      <p>{person.bio}</p>
    </article>

    <picture id="commander-image">
      <source srcSet={require(`../${person.images.webp}`)} type="image/webp" />
      <img src={require(`../${person.images.png}`)} alt={person.name} />
    </picture>
  </main>)
};

export default Crew;
