// nuxt/pages/destination.vue
<script setup lang="ts">
useHead({
  bodyAttrs: {
    class: 'destination'
  },
})
</script>
<template>
  <main id="main" class="grid-container grid-container--destination flow">
    <h1 class="numbered-title"><span aria-hidden="true">01</span> Pick your destination</h1>

    <picture id="moon-image">
      <source srcset="~/assets/destination/image-moon.webp" type="image/webp">
      <img src="~/assets/destination/image-moon.png" alt="the moon">
    </picture>
    <div class="tab-list underline-indicators flex" role="tablist" aria-label="destination list">
      <button aria-selected="true" role="tab" aria-controls="moon-tab" class="uppercase ff-sans-cond text-accent letter-spacing-2" tabindex="0" data-image="moon-image">Moon</button>
      <button aria-selected="false"
              role="tab"
              aria-controls="mars-tab"
              class="uppercase ff-sans-cond text-accent letter-spacing-2"
              tabindex="-1"
              data-image="mars-image">Mars
      </button>
      <button aria-selected="false"
              role="tab"
              aria-controls="europa-tab"
              class="uppercase ff-sans-cond text-accent letter-spacing-2"
              tabindex="-1"
              data-image="europa-image">Europa
      </button>
      <button class="uppercase ff-sans-cond text-accent letter-spacing-2"
              aria-selected="false"
              role="tab"
              aria-controls="titan-tab"
              tabindex="-1"
              data-image="titan-image">Titan
      </button>
    </div>
    <article class="destination-info flow" id="moon-tab" tabindex="0" role="tabpanel">
      <h2 class="fs-800 uppercase ff-serif">Moon</h2>

      <p>See our planet as you’ve never seen it before. A perfect relaxing trip away to help
         regain perspective and come back refreshed. While you’re there, take in some history
         by visiting the Luna 2 and Apollo 11 landing sites.</p>

      <div class="destination-meta flex">
        <div>
          <h3 class="text-accent fs-200 uppercase">Avg. distance</h3>
          <p class="ff-serif uppercase">384,400 km</p>
        </div>
        <div>
          <h3 class="text-accent fs-200 uppercase">Est. travel time</h3>
          <p class="ff-serif uppercase">3 days</p>
        </div>
      </div>
    </article>
  </main>
</template>

// react/src/pages/destination.tsx
import React, { useEffect, useState, useMemo } from "react";

import data from "data.json";

const Destination = () => {

  const [active, setActive] = useState(0);

  const destination = useMemo(() => data.destinations[active], [active]);

  useEffect(() => {
    document.body.classList.add("destination");

    return () => {
      document.body.classList.remove("destination");
    }
  });

  return (<main id="main" className="grid-container grid-container--destination flow">
      <h1 className="numbered-title"><span aria-hidden="true">01</span> Pick your destination</h1>

      <picture id="moon-image">
        <source srcSet={require(`../${destination.images.webp}`)} type="image/webp" />
        <img src={require(`../${destination.images.png}`)} alt={`the ${destination.name}`} />
      </picture>

      <div className="tab-list underline-indicators flex" role="tablist" aria-label="destination list">
        {data.destinations.map((item, index) => {
          return (
            <button className="uppercase ff-sans-cond text-accent letter-spacing-2"
                    aria-selected={active === index ? "true" : "false"}
                    onClick={() => setActive(index)}
                    key={item.name}
                    role="tab">{item.name}
            </button>
          );
        })}
      </div>

      <article className="destination-info flow">
        <h2 className="fs-800 uppercase ff-serif">{destination.name}</h2>
        <p>{destination.description}</p>
        <div className="destination-meta flex">
          <div>
            <h3 className="text-accent fs-200 uppercase">Avg. distance</h3>
            <p className="ff-serif uppercase">{destination.distance}</p>
          </div>
          <div>
            <h3 className="text-accent fs-200 uppercase">Est. travel time</h3>
            <p className="ff-serif uppercase">{destination.travel}</p>
          </div>
        </div>
      </article>
    </main>
  );
};

export default Destination;
