// nuxt/pages/technology.vue
<script setup lang="ts">
useHead({
  bodyAttrs: {
    class: 'technology'
  },
})
</script>
<template>
  <main id="main" class="grid-container grid-container--technology flow">
    <h1 class="numbered-title"><span aria-hidden="true">03</span> Space launch 101</h1>

    <div class="dot-indicators-2 flex" role="tablist" aria-label="technology list">
      <button class="ff-serif fs-600"
              aria-selected="true"
              role="tab"
              aria-controls="capsule-tab"
              tabindex="0"
              data-image="capsule-image">1
      </button>
      <button class="ff-serif fs-600"
              aria-selected="false"
              role="tab"
              aria-controls="spaceport-tab"
              tabindex="-1"
              data-image="spaceport-image">2
      </button>
      <button class="ff-serif fs-600"
              aria-selected="false"
              role="tab"
              aria-controls="space-capsule-tab"
              tabindex="-1"
              data-image="space-capsule-image">3
      </button>
    </div>

    <article class="technology-details flow" id="capsule-tab" role="tabpanel" tabindex="0">
      <header>
        <h2 class="text-accent fs-300 ff-serif uppercase">The terminology...</h2>
        <p class="fs-700 uppercase ff-serif">Launch vehicle</p>
      </header>
      <p>A launch vehicle or carrier rocket is a rocket-propelled vehicle used to carry a
         payload from Earth's surface to space, usually to Earth orbit or beyond. Our
         WEB-X carrier rocket is the most powerful in operation. Standing 150 metres tall,
         it's quite an awe-inspiring sight on the launch pad!</p>
    </article>

    <picture id="capsule-image">
      <img class="landscape" src="~/assets/technology/image-launch-vehicle-landscape.jpg" alt="Launch Vehicle">
      <img class="portrait" src="~/assets/technology/image-launch-vehicle-portrait.jpg" alt="Launch Vehicle">
    </picture>
  </main>
</template>

// react/src/pages/technology.tsx
import React, { useEffect, useState, useMemo } from "react";

import data from "data.json";

const Technology = () => {

  const [active, setActive] = useState(0);

  const technology = useMemo(() => data.technology[active], [active]);

  useEffect(() => {
    document.body.classList.add("technology");

    return () => {
      document.body.classList.remove("technology");
    }
  });

  return (
    <main id="main" className="grid-container grid-container--technology flow">
      <h1 className="numbered-title"><span aria-hidden="true">03</span> Space launch 101</h1>

      <div className="dot-indicators-2 flex" role="tablist" aria-label="technology list">
        {data.technology.map((item, index) => (<button className="ff-serif fs-600"
                                                       key={item.name}
                                                       aria-selected={active === index ? "true" : "false"}
                                                       onClick={() => setActive(index)}
                                                       role="tab">{index}
        </button>))}
      </div>

      <article className="technology-details flow">
        <header>
          <h2 className="text-accent fs-300 ff-serif uppercase">The terminology...</h2>
          <p className="fs-700 uppercase ff-serif">{technology.name}</p>
        </header>
        <p>{technology.description}</p>
      </article>

      <picture id="capsule-image">
        <img className="landscape" src={require(`../${technology.images.landscape}`)} alt={technology.name} />
        <img className="portrait" src={require(`../${technology.images.portrait}`)} alt={technology.name} />
      </picture>
    </main>)
};

export default Technology;
