// angular/src/app/technology/technology.component.ts
import { Component, OnInit } from '@angular/core';
import { TechnologyService, ITechnologyItem } from "../technology.service";

@Component({
  selector: 'app-technology',
  templateUrl: './technology.component.html',
  styleUrls: ['./technology.component.scss']
})
export class TechnologyComponent implements OnInit {
  items: ITechnologyItem[] = [];
  active: number = 0;
  activeItem?: ITechnologyItem;

  constructor(private technologyService: TechnologyService) {}

  ngOnInit(): void {
    window.document.body.classList.add("technology");

    this.items = this.technologyService.getItems();
    this.activeItem = this.items[this.active];
  }

  ngOnDestroy(): void {
    window.document.body.classList.remove("technology");
  }

  change(index: number) {
    this.active = index;
    this.activeItem = this.items[this.active];
  }
}

<main id="main" class="grid-container grid-container--technology flow">
  <h1 class="numbered-title"><span aria-hidden="true">03</span> Space launch 101</h1>

  <div class="dot-indicators-2 flex" role="tablist" aria-label="technology list">
    <button class="ff-serif fs-600"
            *ngFor="let item of items; index as i;"
            (click)="change(i)"
            [attr.aria-selected]="i === active ? 'true' : 'false'"
            role="tab">{{i + 1}}
    </button>
  </div>
  <article class="technology-details flow">
    <header>
      <h2 class="text-accent fs-300 ff-serif uppercase">The terminology...</h2>
      <p class="fs-700 uppercase ff-serif">{{activeItem && activeItem.name}}</p>
    </header>
    <p>{{activeItem && activeItem.description}}</p>
  </article>
  <picture id="capsule-image">
    <img class="landscape" src="{{activeItem && activeItem.images.landscape}}" alt="{{activeItem && activeItem.name}}">
    <img class="portrait" src="{{activeItem && activeItem.images.portrait}}" alt="{{activeItem && activeItem.name}}">
  </picture>
</main>

// react/src/pages/technology.tsx
import React, { useEffect, useState, useMemo } from "react";

import data from "data.json";

const Technology = () => {

  const [active, setActive] = useState(0);

  const technology = useMemo(() => data.technology[active], [active]);

  useEffect(() => {
    document.body.classList.add("technology");

    return () => {
      document.body.classList.remove("technology");
    }
  });

  return (
    <main id="main" className="grid-container grid-container--technology flow">
      <h1 className="numbered-title"><span aria-hidden="true">03</span> Space launch 101</h1>

      <div className="dot-indicators-2 flex" role="tablist" aria-label="technology list">
        {data.technology.map((item, index) => (<button className="ff-serif fs-600"
                                                       key={item.name}
                                                       aria-selected={active === index ? "true" : "false"}
                                                       onClick={() => setActive(index)}
                                                       role="tab">{index}
        </button>))}
      </div>

      <article className="technology-details flow">
        <header>
          <h2 className="text-accent fs-300 ff-serif uppercase">The terminology...</h2>
          <p className="fs-700 uppercase ff-serif">{technology.name}</p>
        </header>
        <p>{technology.description}</p>
      </article>

      <picture id="capsule-image">
        <img className="landscape" src={require(`../${technology.images.landscape}`)} alt={technology.name} />
        <img className="portrait" src={require(`../${technology.images.portrait}`)} alt={technology.name} />
      </picture>
    </main>)
};

export default Technology;
