// angular/src/app/destination/destination.component.ts
import { Component, OnInit } from '@angular/core';
import { DestinationService, IDestinationItem } from "../destination.service";

@Component({
  selector: 'app-destination',
  moduleId: 'page',
  templateUrl: './destination.component.html',
  styleUrls: ['./destination.component.scss'],
})
export class DestinationComponent implements OnInit {
  items: IDestinationItem[] = [];
  active: number = 0;
  activeItem?: IDestinationItem;

  constructor(private destinationService: DestinationService) {}

  ngOnInit(): void {
    window.document.body.classList.add("destination");

    this.items = this.destinationService.getItems();
    this.activeItem = this.items[this.active];
  }

  ngOnDestroy(): void {
    window.document.body.classList.remove("destination");
  }

  change(index: number) {
    this.active = index;
    this.activeItem = this.items[this.active];
  }
}

<main id="main" class="grid-container grid-container--destination flow">
  <h1 class="numbered-title"><span aria-hidden="true">01</span> Pick your destination</h1>

  <picture id="moon-image">
    <source srcset="{{activeItem && activeItem.images.webp}}" type="image/webp">
    <img src="{{activeItem && activeItem.images.png}}" alt="the {{activeItem && activeItem.name}}">
  </picture>

  <div class="tab-list underline-indicators flex" role="tablist" aria-label="destination list">
    <button class="uppercase ff-sans-cond text-accent letter-spacing-2"
            *ngFor="let item of items; index as i;"
            (click)="change(i)"
            [attr.aria-selected]="i === active ? 'true' : 'false'"
            role="tab">{{item.name}}
    </button>
  </div>
  <article class="destination-info flow">
    <h2 class="fs-800 uppercase ff-serif">{{activeItem && activeItem.name}}</h2>

    <p>{{activeItem && activeItem.description}}</p>

    <div class="destination-meta flex">
      <div>
        <h3 class="text-accent fs-200 uppercase">Avg. distance</h3>
        <p class="ff-serif uppercase">{{activeItem && activeItem.distance}}</p>
      </div>
      <div>
        <h3 class="text-accent fs-200 uppercase">Est. travel time</h3>
        <p class="ff-serif uppercase">{{activeItem && activeItem.travel}}</p>
      </div>
    </div>
  </article>
</main>

// next/src/app/destination/page.tsx
'use client';

import { useState, useMemo, useEffect } from "react";
import axios from "axios";

import BodyClass from "@/app/components/BodyClass";

interface IDestinationsItem {
  description: string;
  distance: string;
  name: string;
  travel: string;
  images: {
    webp: string;
    png: string;
  }
}

export default function Page() {
  const [data, setData] = useState<IDestinationsItem[]>([]);
  const [active, setActive] = useState<number>(0);

  const item: IDestinationsItem | false = useMemo(() => data.length > 0 && data[active], [data, active]);

  useEffect(() => {
    getData();
  }, [])

  const getData = async () => {
    const {data} = await axios.get('/api/destinations')
    setData(data);
  }

  return (
    <main id="main" className="grid-container grid-container--destination flow">
      <BodyClass bodyClass="destination" />
      <h1 className="numbered-title"><span aria-hidden="true">01</span> Pick your destination</h1>

      {item && <>
        <picture>
          <source srcSet={item.images.webp} type="image/webp" />
          <img src={item.images.png} alt={item.name} />
        </picture>

        <div className="tab-list underline-indicators flex">
          {data.map((item: IDestinationsItem, index: number) => (
            <button onClick={() => setActive(index)}
                    aria-selected={index === active ? 'true' : 'false'}
                    role="tab"
                    key={index}
                    className="uppercase ff-sans-cond text-accent letter-spacing-2">{item.name}
            </button>
          ))}
        </div>
        <article className="destination-info flow">
          <h2 className="fs-800 uppercase ff-serif">{item.name}</h2>

          <p>{item.description}</p>

          <div className="destination-meta flex">
            <div>
              <h3 className="text-accent fs-200 uppercase">Avg. distance</h3>
              <p className="ff-serif uppercase">{item.distance}</p>
            </div>
            <div>
              <h3 className="text-accent fs-200 uppercase">Est. travel time</h3>
              <p className="ff-serif uppercase">{item.travel}</p>
            </div>
          </div>
        </article>
      </>}
    </main>
  );
}
