// react/src/pages/home.tsx
import React, { useEffect } from "react";
import { NavLink } from "react-router-dom";

const Home = () => {

  useEffect(() => {
    document.body.classList.add("home");

    return () => {
      document.body.classList.remove("home");
    }
  });

  return <main id="main" className="grid-container grid-container--home">
    <div>
      <h1 className="text-accent fs-500 ff-sans-cond uppercase letter-spacing-1">So, you want to travel to
        <span className="d-block fs-900 ff-serif text-white">Space</span></h1>

      <p>Let’s face it; if you want to go to space, you might as well genuinely go to
         outer space and not hover kind of on the edge of it. Well sit back, and relax
         because we’ll give you a truly out of this world experience! </p>
    </div>
    <div>
      <NavLink to={"/destination"} className="large-button uppercase ff-serif text-dark bg-white">Explore</NavLink>
    </div>
  </main>
};

export default Home;

// angular/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  constructor() {}

  ngOnInit(): void {
    window.document.body.classList.add("home");
  }

  ngOnDestroy(): void {
    window.document.body.classList.remove("home");
  }

}

<main id="main" class="grid-container grid-container--home">
  <div>
    <h1 class="text-accent fs-500 ff-sans-cond uppercase letter-spacing-1">So, you want to travel to
      <span class="d-block fs-900 ff-serif text-white">Space</span></h1>

    <p>Let’s face it; if you want to go to space, you might as well genuinely go to
       outer space and not hover kind of on the edge of it. Well sit back, and relax
       because we’ll give you a truly out of this world experience! </p>
  </div>
  <div>
    <a routerLink="/destination" class="large-button uppercase ff-serif text-dark bg-white">Explore</a>
  </div>
</main>
